dist: xenial
language:
  - python

    #python:
    #  - "3.7"

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - gcc-5
      - g++-5
      - cmake

before_install:
  - gcc --version
  - cmake --version
  - python --version
  - sudo apt-get update
  - pip install --user -U pytest

jobs:
  include:
    -python: "3.7"

script:
  - python3 --version
  # Creating the build directory
  - cd src && mkdir build
  - cd build
  # Building using CMake
  - cmake ..
  - make
  - make install
  # Running tests
  - make test
