os: linux
dist: xenial

language:
  - python

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - gcc-5
      - g++-5
      - cmake

before_install:
  - gcc --version
  - cmake --version
  - python --version
  - sudo apt-get update
  - pip install -U pytest

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

script:
  # Creating the build directory
  - mkdir build
  - cd build
  # Building using CMake
  - cmake ..
  - make
  - make install
  # Running tests
  - make test
