dist: xenial
language:
  - cpp
  - python

python:
  - "3.7"

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - gcc-5
      - g++-5
      - cmake

before_install:
  - gcc --version
  - cmake --version
  - python --version
  - pip install --user -U pytest

script:
  # Creating the build directory
  - cd src && mkdir build
  - cd build
  # Building using CMake
  - cmake ..
  - make
  - make install
  # Running tests
  - make test
