os: linux
language: python

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - gcc-5
      - g++-5
      - cmake

before_install:
  - gcc --version
  - cmake --version
  - python --version
  - sudo apt-get update

install:
  - pip install -r requirements.txt

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    #- python: "3.5"
    #  dist:
    #    - xenial
    #    - bionic
    #- python: "3.6"
    #- python: "3.7"
    #- python: "3.8"
    - dist: xenial
    - dist: bionic

script:
  # Creating the build directory
  - mkdir build
  - cd build
  # Building using CMake
  - cmake ..
  - make
  - make install

after_script:
  # Running tests
  # Cpp tests
  - make test
  # Python tests
  - cd .. && pytest morphac
