version: 2.1

jobs:
  install_and_test:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - run:
          name: Install
          command: |
            python --version
            pip install morphac
      - run:
          name: Test
          command: |
            python -c "import morphac; print(morphac.__version__); morphac.run_all_tests()"

workflows:
  install_and_test:
    jobs:
      - install_and_test
