version: 2.1

jobs:
  install:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - run:
          name: Install
          command: |
            python --version
            pip install morphac

workflows:
  install_and_test:
    jobs:
      - install
