version: 2.1

jobs:
  install_and_test:
    parameters:
      python_image:
        type: string
    docker:
      - image: << parameters.python_image >>
    steps:
      - run:
          name: Install
          command: |
            python --version
            sudo pip install morphac
      - run:
          name: Test
          command: |
            python -c "import morphac; print(morphac.__version__); morphac.run_all_tests()"

workflows:
  install_and_test:
    triggers:
      - schedule:
          # 12 am PT = 7 am UTC.
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - install_and_test:
          matrix:
            parameters:
              python_image:
                [
                  circleci/python:3.6.8,
                  circleci/python:3.7.8,
                  circleci/python:3.8.5,
                ]
