version: 2.1

jobs:
  install:
    docker:
      - image: circleci/python:3.6.8
      #image: ubuntu-1604:202007-01
    steps:
      - run:
        name: Install
        command: pip install morphac


workflows:
  main:
    jobs:
      - install
